sudo: required

services:
  - docker

env:
  - PYTHON_BIN=python2.7
  - PYTHON_BIN=python3

script:
  - docker run --rm -i -t -v `pwd`:/app:Z -w /app celery4_dashboard_local $PYTHON_BIN -m pytest tests/ -svx
  - docker run --rm -i -t -v `pwd`:/app:Z -w /app celery3_dashboard_local $PYTHON_BIN -m pytest tests/ -svx
